//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobile_store.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_KhachHang()
        {
            this.tb_DonHang = new HashSet<tb_DonHang>();
        }
        [Display(Name = "Mã Khách Hàng")]//Thuộc tính display thay đổi tên 
        public int MaKH { get; set; }
        [Display(Name = "Họ Và Tên")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string HoTen { get; set; }
        [Display(Name = "Username")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string TaiKhoan { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string MatKhau { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string Email { get; set; }
        [Display(Name = "Địa Chỉ")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string Diachi { get; set; }
        [Display(Name = "Điện Thoại")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string DienThoai { get; set; }
        [Display(Name = "Giới tính")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày Sinh")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Display(Name = "Đơn Hàng")]
        [Required(ErrorMessage = "{0} Không được để trống")]//Kiểm tra trống 
        public virtual ICollection<tb_DonHang> tb_DonHang { get; set; }
    }
}
